apiVersion: v1
kind: PersistentVolume
metadata:
  name: generated-images-llmmllab
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/generated-images
    type: DirectoryOrCreate
  claimRef:
    namespace: llmmllab
    name: generated-images
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lsnode-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generated-images
  namespace: llmmllab
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-base-llmmllab
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/code-base
    type: DirectoryOrCreate
  claimRef:
    namespace: llmmllab
    name: code-base
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lsnode-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-base
  namespace: llmmllab
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
