

from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ChatCompletionRequestMessageContentPartRefusal(BaseModel):
    refusal: Annotated[str, Field(..., description="The refusal message generated by the model.")]
    """The refusal message generated by the model."""
    type: Annotated[Literal["refusal"], Field(..., description="The type of the content part.")]
    """The type of the content part."""

    model_config = ConfigDict(extra="ignore")