

from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class MessageContentRefusalObject(BaseModel):
    """The refusal content generated by the assistant."""
    refusal: Annotated[str, Field(...)]
    type: Annotated[Literal["refusal"], Field(..., description="Always `refusal`.")]
    """Always `refusal`."""

    model_config = ConfigDict(extra="ignore")